"""Remove Comment|Pitch Relationship

Revision ID: 52441e922b42
Revises: 7e9f1b732fdc
Create Date: 2019-05-29 16:06:40.382873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52441e922b42'
down_revision = '7e9f1b732fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
