"""Remove Comment|Pitch Relationship

Revision ID: 7e9f1b732fdc
Revises: ba51a4681cf9
Create Date: 2019-05-29 16:03:42.179390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9f1b732fdc'
down_revision = 'ba51a4681cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_comment_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_comment_id_fkey', 'users', 'comments', ['comment_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'username')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
